Tetrangles/Models/ErrorViewModel.cs
using System;

namespace Tetrangles.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tetrangles/Controllers/CarportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Tetrangles.Controllers
{
    public class CarportController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Tetrangles/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Tetrangles.Models;

namespace Tetrangles.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult RealEstate()
        {
            return View();
        }

        public IActionResult Rent()
        {
            return View();
        }
        public IActionResult Steel()
        {
            return View();
        }
    }
}

Tetrangles/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Tetrangles.Controllers
{
    public class RentController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }
    }
}

Tetrangles/Views/Carport/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4 mt-5 pt-3">
            <h2 class="text-center mb-4" style="letter-spacing:0.05em;line-height:1.7em;font-family:'Nunito',sans-serif;font-size:29px;">PORTFOLIO</h2>
        </div>
        <div class="col-md-4"></div>
    </div>
    <div class="container" style="max-width:780px;">
        <div class="row mb-5">
            <div class="col-md-4" style="height:150px;">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" style="height:200px;" />
                    <h4 class="mt-3">Image 1</h4>
                    <p>Description of Image 1</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" />
                    <h4 class="mt-3">Image 2</h4>
                    <p>Description of Image 2</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" style="height:200px;" />
                    <h5 class="mt-3">Image 3</h5>
                    <p>Description of Image 3</p>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-4" style="height:150px;">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" style="height:200px;" />
                    <h4 class="mt-3">Image 1</h4>
                    <p>Description of Image 1</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" style="height:280px;" />
                    <h4 class="mt-3">Image 2</h4>
                    <p>Description of Image 2</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" />
                    <h5 class="mt-3">Image 3</h5>
                    <p>Description of Image 3</p>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-4" style="height:150px;">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" style="height:200px;" />
                    <h4 class="mt-3">Image 1</h4>
                    <p>Description of Image 1</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" />
                    <h4 class="mt-3">Image 2</h4>
                    <p>Description of Image 2</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow text-center bg-white pb-3">
                    <img class="img-fluid" src="~/img/img.jpeg" style="height:280px;" />
                    <h5 class="mt-3">Image 3</h5>
                    <p>Description of Image 3</p>
                </div>
            </div>
        </div>
    </div>

Tetrangles/Views/Home/RealEstate.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
    <div class="row bg-light mb-5 pb-5 pt-5">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h1 class="page-header mt-5 ml-5 pb-3 pt-3" style="font-family:'Nunito',sans-serif;font-size:40px;">Real Estate</h1>
           <div class="text-center mb-5" data-border-width="5" style="transform-origin: center 5px;width:60px;height:10px;
        background-color:rgba(237, 205, 31, 1);position:relative;left:40px;bottom:10px"></div>
        </div>
        <div class="col-md-1"></div>
    </div>
    <div class="row mb-5">
        <div class="col-md-1"></div>
        <div class="col-md-5">
            <p class="mt-5 ml-5 mb-5" style="font-family:Helvetica, sans-serif;font-size:17px;line-height:1.7em;font-weight:200;">
                I'm a paragraph. Click here to add your own text and edit me. It’s easy.
                Just click “Edit Text” or double click me to add your own content and
                make changes to the font. Feel free to drag and drop me anywhere you like on your page.
                I’m a great place for you to tell a story and let your users know a little more about you.
                This is a great space to write long text about your company and your services. You can use
                this space to go into a little more detail about your company. Talk about your team and
                what services you provide. Tell your visitors the story of how you came up with the idea for
                your business and what makes you different from your competitors. Make your company stand out
                and show your visitors who you are.
            </p>
            <a asp-controller="Home" asp-action="Index" class="btn bg-dark text-warning ml-5 mb-5 pb-3 pt-3 pr-3 pl-3">Go Back Home</a>
        </div>
        <div class="col-md-5">
            <img class="img-fluid" src="~/img/projects/proj.jpg" style="width:100%;height:100%;"/>
        </div>
        <div class="col-md-1"></div>
    </div>

Tetrangles/Views/Home/Rent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row bg-light mb-5 pb-5 pt-5" style="overflow:hidden;">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <h1 class="page-header mt-5 ml-5 pb-3 pt-3" style="font-family:'Nunito',sans-serif;font-size:40px;">Facility Managment</h1>
        <div class="text-center mb-5" data-border-width="5" style="transform-origin: center 5px;width:60px;height:10px;
        background-color:rgba(237, 205, 31, 1);position:relative;left:40px;bottom:10px"></div>
    </div>
    <div class="col-md-1"></div>
</div>
<div class="row mb-5" style="overflow:hidden;">
    <div class="col-md-1"></div>
    <div class="col-md-5">
        <p class="mt-5 ml-5 mb-5" style="font-family:Helvetica, sans-serif;font-size:17px;line-height:1.7em;font-weight:200;">
            I'm a paragraph. Click here to add your own text and edit me. It’s easy.
            Just click “Edit Text” or double click me to add your own content and
            make changes to the font. Feel free to drag and drop me anywhere you like on your page.
            I’m a great place for you to tell a story and let your users know a little more about you.
            This is a great space to write long text about your company and your services. You can use
            this space to go into a little more detail about your company. Talk about your team and
            what services you provide. Tell your visitors the story of how you came up with the idea for
            your business and what makes you different from your competitors. Make your company stand out
            and show your visitors who you are.
        </p>
        <a asp-controller="Home" asp-action="Index" class="btn bg-dark text-warning ml-5 mb-5 pb-3 pt-3 pr-3 pl-3">Go Back Home</a>
    </div>
    <div class="col-md-5">
        <img class="img-fluid" src="~/img/projects/proj.jpg" style="width:100%;height:100%;" />
    </div>
    <div class="col-md-1"></div>
</div>@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Tetrangles/Views/Home/Steel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row bg-light mb-5 pb-5 pt-5">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <h1 class="page-header mt-5 ml-5 pb-3 pt-3" style="font-family:'Nunito',sans-serif;font-size:40px;">Steel Works</h1>
        <div class="text-center mb-5" data-border-width="5" style="transform-origin: center 5px;width:60px;height:10px;
        background-color:rgba(237, 205, 31, 1);position:relative;left:40px;bottom:10px"></div>
    </div>
    <div class="col-md-1"></div>
</div>
<div class="row mb-5">
    <div class="col-md-1"></div>
    <div class="col-md-5">
        <p class="mt-5 ml-5 mb-5" style="font-family:Helvetica, sans-serif;font-size:17px;line-height:1.7em;font-weight:200;">
            I'm a paragraph. Click here to add your own text and edit me. It’s easy.
            Just click “Edit Text” or double click me to add your own content and
            make changes to the font. Feel free to drag and drop me anywhere you like on your page.
            I’m a great place for you to tell a story and let your users know a little more about you.
            This is a great space to write long text about your company and your services. You can use
            this space to go into a little more detail about your company. Talk about your team and
            what services you provide. Tell your visitors the story of how you came up with the idea for
            your business and what makes you different from your competitors. Make your company stand out
            and show your visitors who you are.
        </p>
        <a asp-controller="Home" asp-action="Index" class="btn bg-dark text-warning ml-5 mb-5 pb-3 pt-3 pr-3 pl-3">Go Back Home</a>
    </div>
    <div class="col-md-5">
        <img class="img-fluid" src="~/img/projects/proj.jpg" style="width:100%;height:100%;" />
    </div>
    <div class="col-md-1"></div>
</div>

Tetrangles/Views/Rent/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
    <div class="row pt-5 pb-3 bg-light mb-5">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h1 class="page-header mt-5 mb-3">Houses For Rent</h1>
        </div>       
        <div class="col-md-2"></div>
    </div>
<div class="row mt-5">
    <div class="col-md-2"></div>
    <div class="col-md-2">
        <img src="~/img/projects/rooms.jpg"  class="img-fluid" />
    </div>
    <div class="col-md-4">
        <h2>4 Bed Room Duplex</h2>
        <p style="font-weight:100;">
            Our Standard Rooms are the perfect combination of function and comfort.
        </p>
        <ul style="font-weight:100;margin-left:0px;padding-left:inherit;">
            <li>
                Size: 230 sq ft
            </li>
            <li>
                Beds: 1 Double(s)
            </li>
        </ul>
        <hr />
    </div>
    <div class="col-md-2 mt-2">
            <span class="text-center d-flex justify-content-center mt-5" style="font-size:35px;">$3500/yr</span><br />   
        <button class="btn btn-block text-warning bg-dark mt-2" style="border-radius:0px;">More Info</button>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row mt-5">
    <div class="col-md-2"></div>
    <div class="col-md-2">
        <img src="~/img/projects/rooms.jpg" class="img-fluid" />
    </div>
    <div class="col-md-4">
        <h2>4 Bed Room Duplex</h2>
        <p style="font-weight:100;">
            Our Standard Rooms are the perfect combination of function and comfort.
        </p>
        <ul style="font-weight:100;margin-left:0px;padding-left:inherit;">
            <li>
                Size: 230 sq ft
            </li>
            <li>
                Beds: 1 Double(s)
            </li>
        </ul>
        <hr />
    </div>
    <div class="col-md-2 mt-2">
        <span class="text-center d-flex justify-content-center mt-5" style="font-size:35px;">$3500/yr</span><br />
        <button class="btn btn-block text-warning bg-dark mt-2" style="border-radius:0px;">More Info</button>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row mt-5">
    <div class="col-md-2"></div>
    <div class="col-md-2">
        <img src="~/img/projects/rooms.jpg" class="img-fluid" />
    </div>
    <div class="col-md-4">
        <h2>4 Bed Room Duplex</h2>
        <p style="font-weight:100;">
            Our Standard Rooms are the perfect combination of function and comfort.
        </p>
        <ul style="font-weight:100;margin-left:0px;padding-left:inherit;">
            <li>
                Size: 230 sq ft
            </li>
            <li>
                Beds: 1 Double(s)
            </li>
        </ul>
        <hr />
    </div>
    <div class="col-md-2 mt-2">
        <span class="text-center d-flex justify-content-center mt-5" style="font-size:35px;">$3500/yr</span><br />
        <button class="btn btn-block text-warning bg-dark mt-2" style="border-radius:0px;">More Info</button>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row mt-5">
    <div class="col-md-2"></div>
    <div class="col-md-2">
        <img src="~/img/projects/rooms.jpg" class="img-fluid" />
    </div>
    <div class="col-md-4">
        <h2>4 Bed Room Duplex</h2>
        <p style="font-weight:100;">
            Our Standard Rooms are the perfect combination of function and comfort.
        </p>
        <ul style="font-weight:100;margin-left:0px;padding-left:inherit;">
            <li>
                Size: 230 sq ft
            </li>
            <li>
                Beds: 1 Double(s)
            </li>
        </ul>
        <hr />
    </div>
    <div class="col-md-2 mt-2">
        <span class="text-center d-flex justify-content-center mt-5" style="font-size:35px;">$3500/yr</span><br />
        <button class="btn btn-block text-warning bg-dark mt-2" style="border-radius:0px;">More Info</button>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row mt-5 mb-5">
    <div class="col-md-2"></div>
    <div class="col-md-2">
        <img src="~/img/projects/rooms.jpg" class="img-fluid" />
    </div>
    <div class="col-md-4">
        <h2>4 Bed Room Duplex</h2>
        <p style="font-weight:100;">
            Our Standard Rooms are the perfect combination of function and comfort.
        </p>
        <ul style="font-weight:100;margin-left:0px;padding-left:inherit;">
            <li>
                Size: 230 sq ft
            </li>
            <li>
                Beds: 1 Double(s)
            </li>
        </ul>
        <hr />
    </div>
    <div class="col-md-2 mt-2">
        <span class="text-center d-flex justify-content-center mt-5" style="font-size:35px;">$3500/yr</span><br />
        <a asp-controller="Rent" asp-action="Details" class="btn btn-block text-warning bg-dark mt-2" style="border-radius:0px;">More Info</a>
    </div>
    <div class="col-md-2"></div>
</div>

Tetrangles/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tetrangles</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" type="text/css" href="~/icons/font/flaticon.css" />

    <style>



        a:active {
            color: red !important;
        }

        a:hover {
            color: green;
        }

        .overlay {
            position: absolute;
            bottom: 100%;
            left: 0;
            right: 0;
            background-color: #fff;
            overflow: hidden;
            width: 100%;
            height: 0;
            transition: .5s ease;
            opacity: 0.8;
        }

        input, textarea {
            background-color: rgba(247, 247, 247, 1) !important;
        }

        form > .btn {
        }

        .house:hover .overlay {
            bottom: 0;
            height: 100%;
        }

        .rent:hover .overlay {
            bottom: 0;
            height: 100%;
        }

        .carport:hover .overlay {
            bottom: 0;
            height: 100%;
        }

        .steel:hover .overlay {
            bottom: 0;
            height: 100%;
        }

        .text {
            color: black;
            font-size: 20px;
            position: absolute;
            top: 50%;
            left: 50%;
            -webkit-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            text-align: center;
        }

        .navbar-brand img {
            width: 150px;
            height: 80px;
        }

        .navbar-toggler-icon {
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light pt-0 pb-0" style="background-color:rgba(30, 45, 59, 1);">
            <a class="navbar-brand pt-0 pb-0" asp-controller="Home" asp-action="Index">
                <img src="~/img/logo.jpeg" class="img-fluid align-top" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto" style="font-family:'Nunito',sans-serif;font-size:1.2em;font-weight:100;">
                    <li class="nav-item active pr-5">
                        <a class="nav-link text-light" href="#">HOME <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item pr-5">
                        <a class="nav-link text-light" href="#services">SERVICES</a>
                    </li>
                    <li class="nav-item pr-5">
                        <a class="nav-link text-light" href="#about">ABOUT</a>
                    </li>
                    <li class="nav-item pr-5">
                        <a class="nav-link text-light" href="#projects">PROJECTS</a>
                    </li>
                    <li class="nav-item pr-5">
                        <a class="nav-link text-light" href="#contactus">CONTACT US</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!--   <nav style="margin-bottom:0px !important;height:80px;background-color:rgba(30, 45, 59, 1) !important;" class="navbar navbar-expand-lg navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
           <div class="container">
               <div class="col-md-7">
                   <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                       <img src="~/img/logo.jpeg" class="img-fluid align-top" />
                   </a>
                   <button class="navbar-toggler float-right mt-4" type="button" data-toggle="collapse" data-target="#toggleNavbar" aria-controls="navbarSupportedContent"
                           aria-expanded="false" aria-label="Toggle navigation">
                       <span class="navbar-toggler-icon"></span>
                   </button>
               </div>
               <div class="col-md-5" style="max-width:50%;">

                   <div class="collapse navbar-collapse d-sm-inline-flex flex-sm-row-reverse" id="toggleNavbar">
                       <partial name="_LoginPartial" />
                       <ul class="navbar-nav flex-grow-1" style="font:'Nunito',sans-serif;font-size:1.2em;font-weight:200;">
                           <li class="nav-item pr-5">
                               <a class="nav-link active text-light" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                           </li>
                           <li class="nav-item pr-5">
                               <a class="nav-link text-light" href="#services" style="transition:color 0.4s ease 0s;">SERVICES</a>
                           </li>
                           <li class="nav-item pr-5">
                               <a class="nav-link text-light" href="#about">ABOUT</a>
                           </li>
                           <li class="nav-item pr-5">
                               <a class="nav-link text-light" href="#projects">PROJECTS</a>
                           </li>
                           <li class="nav-item pr-5">
                               <a class="nav-link text-light" href="#contactus" style="transition:color 0.4s ease 0s;">CONTACT</a>
                           </li>
                       </ul>
                   </div>
               </div>
           </div>
       </nav>-->
    </header>
    <div class="container" style="max-width:1280px !important;padding:0px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Tetrangles Projects Limited -
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!---->
</body>
</html>